sudo: required

language: node_js

node_js:
  - lts/*

services:
  - docker
  - redis-server
  
before_install: 
  - docker build -t alisaidgunes/focus .

script: 
 - echo "skipping tests"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push alisaidgunes/focus
