sudo: required

language: node_js

node_js:
  - lts/*
services:
  - docker
before_install: 
  - docker-compose up --build
script: 
  - yarn test
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker-compose push alisaidgunes/focusbackend
