version: '3.9'

services:

  mongo_db:
    image: mongo:latest
    container_name: db_container
    volumes:
      - mongo_db:/data/db
    restart: always
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - redis:/data/db
    restart: always

  api:
    build: .
    container_name: api_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
      - redis
    restart: always
volumes:
  mongo_db: {}
  redis: {}