branch-defaults:
  master:
    environment: BRANCHNAME-my-application
global:
  application_name: FocusBackend
  default_ec2_keyname: XXXXXX
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  sc: git