version: 2
jobs:
  build:
    docker:
      - image: node:alpine
      - image: mongo:latest
      - image: redis:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn ci:test

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            apk update && apk add curl curl-dev
            set -x
            VER="19.03.13"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: yarn ci:docker

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout

      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt update && sudo apt upgrade
            sudo apt-get install wget build-essential checkinstall
            sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev \ libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
            cd /usr/src
            sudo wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz
            sudo tar xzf Python-3.7.9.tgz
            cd Python-3.7.9
            sudo ./configure --enable-optimizations
            sudo make altinstall
            sudo python3 --version
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo pip install awsebcli --upgrade --user

      - run:
          name: Deploying
          command: eb deploy $CIRCLE_BRANCH-my-application

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy
