version: 2
jobs:
  build:
    docker:
      - image: node:alpine
      - image: mongo:latest
      - image: redis:latest
      - image: gradientco/node-elastic-beanstalk:7.10.0
      - image: circleci/python:3.7-node-browsers-legacy

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn ci:test

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            apk update && apk add curl curl-dev
            set -x
            VER="19.03.13"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: yarn ci:docker

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout

      - run:
          name: Install Python
          command:
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            echo export PATH=/root/.local/bin/:$PATH >> $BASH_ENV
            echo export PATH=/home/circleci/.local/bin/:$PATH >> $BASH_ENV
      - run:
          name: Install pip
          command: 
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
      - run:
          name: Install AWS EB CLI & S3 CLI
          command: 
            pip install awsebcli --upgrade --user
            pip install awscli --upgrade --user
      - run:
          name: Deploying
          command: eb deploy $CIRCLE_BRANCH-my-application

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy
