version: 2

jobs:
  deploy:
    working_directory: ~/app
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: Install AWS EB CLI & S3 CLI
          command: |

            pyenv versions
            pyenv global 3.7.0
            pip install --upgrade pip
            pip install awsebcli

      - run:
          name: Deploying
          command: eb deploy $CIRCLE_BRANCH-my-application

workflows:
  version: 2
  build:
    jobs:
      - deploy
