version: 2
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: node:alpine
      - image: mongo:latest
      - image: redis:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn ci:test

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run:
          name: Install Docker client
          command: |
            apk update && apk add curl curl-dev
            set -x
            VER="19.03.13"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: yarn ci:docker

  deploy:
      environment-name: $CIRCLE_BRANCH-focusbackend
      label: version-<<pipeline.number>>

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy
